import os
import sys
import re
import json
import logging
import ast
import shutil
import subprocess
import difflib
import dspy
from dspy.teleprompt import MIPROv2, GEPA
from dspy.evaluate import Evaluate
from typing import List, Optional, Callable, Union
from core.prompt_loader import PromptLoader
from core.config_loader import ConfigLoader

try:
    import fitz
except ImportError:
    fitz = None

try:
    from docx import Document as DocxDocument
except ImportError:
    DocxDocument = None

try:
    from bs4 import BeautifulSoup
except ImportError:
    BeautifulSoup = None

try:
    from pptx import Presentation
except ImportError:
    Presentation = None

logger = logging.getLogger(__name__)

# Force huggingface_hub to never make network calls during this process.
# SentenceTransformer checks for model updates via HTTP which can hang.
os.environ.setdefault("HF_HUB_OFFLINE", "1")


# =====================================================================
# DSPY SIGNATURES
# =====================================================================

class DatasetGeneratorSignature(dspy.Signature):
    agent_prompt = dspy.InputField(desc="The system instructions of the agent.")
    supplementary_documents = dspy.InputField(
        desc="Optional reference documentation content to ground the generated scenarios.")
    num_examples = dspy.InputField(desc="Number of test scenarios to generate.")
    json_dataset = dspy.OutputField(
        desc="A raw JSON array of objects with keys 'input_context' and 'gold_response'. No markdown blocks.")


DatasetGeneratorSignature.__doc__ = PromptLoader.get("signatures", "DatasetGeneratorSignature")


class CodeDatasetGeneratorSignature(dspy.Signature):
    python_source_code = dspy.InputField(desc="The active source code of the Python skill file.")
    num_examples = dspy.InputField(desc="Number of test scenarios to generate.")
    json_dataset = dspy.OutputField(desc="A valid, raw JSON array of mock test objects.")


CodeDatasetGeneratorSignature.__doc__ = PromptLoader.get("signatures", "CodeDatasetGeneratorSignature")


class UniversalJudgeSignature(dspy.Signature):
    input_context = dspy.InputField(desc="The input scenario.")
    gold_response = dspy.InputField(desc="The target answer context.")
    agent_prediction = dspy.InputField(desc="The output generated by the prompt to evaluate.")
    verdict = dspy.OutputField(desc="Return 'YES' if agent_prediction is correct, non-trivial, and meaningfully different from gold_response. Return 'NO' if agent_prediction is empty, too short, identical to gold_response, or incorrect.")


UniversalJudgeSignature.__doc__ = PromptLoader.get("signatures", "UniversalJudgeSignature")


class DynamicAgentSignature(dspy.Signature):
    input_context = dspy.InputField(desc="The input text context.")
    output_response = dspy.OutputField(desc="The response matching the system prompt identity.")


DynamicAgentSignature.__doc__ = PromptLoader.get("signatures", "DynamicAgentSignature")


class SpecDocumentationSignature(dspy.Signature):
    raw_description = dspy.InputField(desc="The original short or vague text description property.")
    optimized_description = dspy.OutputField(
        desc="An expanded, high-clarity technical description. Do not modify format parameters.")


SpecDocumentationSignature.__doc__ = PromptLoader.get("signatures", "SpecDocumentationSignature")


class SecurityAuditorSignature(dspy.Signature):
    proposed_prompt = dspy.InputField(desc="The generated prompt variant proposed by MIPROv2.")
    injection_vulnerability_detected = dspy.OutputField(
        desc="Return strictly 'YES' if a security exploit risk exists, otherwise 'NO'.")


SecurityAuditorSignature.__doc__ = PromptLoader.get("signatures", "SecurityAuditorSignature")


class FactGroundingAuditorSignature(dspy.Signature):
    gold_reference = dspy.InputField(desc="The verified, trusted ground truth source facts.")
    agent_prediction = dspy.InputField(desc="The generated output text produced by the agent.")
    contains_false_information = dspy.OutputField(
        desc="Return strictly 'YES' if the agent made up an unverified claim, otherwise 'NO'.")


FactGroundingAuditorSignature.__doc__ = PromptLoader.get("signatures", "FactGroundingAuditorSignature")


class CodeOptimizationSignature(dspy.Signature):
    original_python_code = dspy.InputField(desc="The raw, unoptimized source text of the python skill file.")
    optimized_python_code = dspy.OutputField(
        desc="The fully rewritten, optimized python code block matching the structural interface contract.")


CodeOptimizationSignature.__doc__ = PromptLoader.get("signatures", "CodeOptimizationSignature")


class ContextualJudgeSignature(dspy.Signature):
    source_documentation = dspy.InputField(desc="The reference factual project guide.")
    input_context = dspy.InputField(desc="The user scenario question.")
    gold_response = dspy.InputField(desc="The target reference answer.")
    agent_prediction = dspy.InputField(desc="The prediction output by the agent.")
    verdict = dspy.OutputField(desc="Strict confirmation decision outcome token.")


ContextualJudgeSignature.__doc__ = PromptLoader.get("signatures", "ContextualJudgeSignature")


class DatasetValidatorSignature(dspy.Signature):
    agent_documentation = dspy.InputField(desc="The full system prompt or agent instructions.")
    input_context = dspy.InputField(desc="The test case input scenario.")
    gold_response = dspy.InputField(desc="The expected correct response.")
    is_solvable = dspy.OutputField(desc="Return 'YES' if solvable using the documentation alone, otherwise 'NO'.")
    is_label_correct = dspy.OutputField(desc="Return 'YES' if the gold_response is correct for the input, otherwise 'NO'.")
    hardness_score = dspy.OutputField(desc="Rate 1 to 5: 1=trivial, 3=realistic, 5=complex edge case.")
    is_adversarial = dspy.OutputField(desc="Return 'YES' if this is out-of-scope or adversarial, otherwise 'NO'.")


DatasetValidatorSignature.__doc__ = PromptLoader.get("signatures", "DatasetValidatorSignature")


class UniversalAgentProgram(dspy.Module):
    def __init__(self):
        super().__init__()
        self.predictor = dspy.Predict(DynamicAgentSignature)

    def forward(self, input_context, **kwargs):
        source_context = kwargs.get("source_context", "No context provided.")
        return self.predictor(
            input_context=input_context,
            repository_documentation=source_context
        )


UniversalAgentProgram.__doc__ = PromptLoader.get("signatures", "UniversalAgentProgram")


# =====================================================================
# METRICS
# =====================================================================

def secure_universal_llm_metric(gold, pred, trace=None):
    """A multi-stage secure evaluation metric that prevents prompt injection and false info."""
    pred_text = getattr(pred, 'output_response', str(pred) if pred else "").strip()
    gold_text = getattr(gold, 'output_response', "").strip()

    if not pred_text or len(pred_text) < 3:
        logger.warning("Metric: rejected trivial/empty prediction (len=%d)", len(pred_text))
        return 0.0

    if pred_text == gold_text:
        logger.warning("Metric: rejected exact gold match (echoing)")
        return 0.0

    try:
        if trace is not None and hasattr(trace, 'current_instruction'):
            candidate_prompt = trace.current_instruction
            security_auditor = dspy.Predict(SecurityAuditorSignature)
            security_check = security_auditor(proposed_prompt=candidate_prompt)
            if "YES" in security_check.injection_vulnerability_detected.upper():
                logger.warning(
                    "Security Guard Triggered: Mutation rejected - prompt injection vulnerability risk detected.")
                return 0.0
    except Exception:
        logger.warning("Security auditor LM call failed, defaulting to 0.0")
        return 0.0

    try:
        fact_auditor = dspy.Predict(FactGroundingAuditorSignature)
        fact_check = fact_auditor(
            gold_reference=gold_text,
            agent_prediction=pred_text
        )
        if "YES" in fact_check.contains_false_information.upper():
            logger.warning("Hallucination Guard Triggered: Variant rejected - false claims found.")
            return 0.0
    except Exception:
        logger.warning("Fact auditor LM call failed, defaulting to 0.0")
        return 0.0

    try:
        judge = dspy.Predict(UniversalJudgeSignature)
        result = judge(
            input_context=gold.input_context,
            gold_response=gold_text,
            agent_prediction=pred_text
        )
        return 1.0 if "YES" in result.verdict.upper() else 0.0
    except Exception:
        logger.warning("Judge LM call failed, defaulting to 0.0")
        return 0.0


def universal_llm_metric(gold_example, agent_prediction, trace=None) -> float:
    """Simpler judge metric using contextual judge. Kept for backward compatibility."""
    gold_text = gold_example.gold_response
    pred_text = getattr(agent_prediction, 'output_response', str(agent_prediction))
    input_text = gold_example.input_context
    associated_context = getattr(gold_example, 'source_context', "")

    judge = dspy.Predict(ContextualJudgeSignature)
    try:
        response = judge(
            source_documentation=associated_context,
            input_context=input_text,
            gold_response=gold_text,
            agent_prediction=pred_text
        )
        verdict = response.verdict.strip().upper()
        return 1.0 if re.search(r"\bYES\b", verdict) else 0.0
    except Exception as e:
        logger.error(f"Universal judge metric failed: {str(e)}")
        return 0.0


# =====================================================================
# DATASET UTILITIES
# =====================================================================

def extract_and_load_dataset(raw_output: str) -> list:
    """Parse LLM JSON output into a list of dspy.Example objects with fallback handling."""
    json_clean = re.sub(r"^```json|```$", "", raw_output, flags=re.MULTILINE).strip()

    try:
        raw_json_data = json.loads(json_clean)
    except Exception:
        try:
            raw_json_data = ast.literal_eval(json_clean)
        except Exception:
            array_match = re.search(r"(\[\s*\{[\s\S]*?\}\s*\])", raw_output)
            if array_match:
                try:
                    raw_json_data = ast.literal_eval(array_match.group(1))
                except Exception:
                    raw_json_data = []
            else:
                raw_json_data = []

    if not raw_json_data or not isinstance(raw_json_data, list):
        raw_json_data = [
            {"input_context": "Write a short creative stanza.",
             "gold_response": "The gears turn quietly inside the machine."},
            {"input_context": "Draft a short poetic line.",
             "gold_response": "Neon reflections dancing in wet asphalt lanes."}
        ]
    return [
        dspy.Example(input_context=i.get("input_context", ""), output_response=i.get("gold_response", "")).with_inputs(
            "input_context") for i in raw_json_data]


def chunk_text(text: str, chunk_size: int = 4000, chunk_overlap: int = 200) -> list:
    """Split text into overlapping chunks for processing large documents."""
    if not text or len(text) <= chunk_size:
        return [text] if text else []
    chunks = []
    start = 0
    while start < len(text):
        end = min(start + chunk_size, len(text))
        chunks.append(text[start:end])
        start += chunk_size - chunk_overlap
    return chunks


def generate_dataset_via_lm(
    lm_client,
    agent_prompt: str,
    num_examples: int = 5,
    supplementary_docs: str = "",
    chunk_size: int = 0,
    chunk_overlap: int = 200,
) -> list:
    """Generate a synthetic dataset via direct LM call, with automatic chunking
    for large supplementary documents."""
    if not supplementary_docs:
        return _generate_single(lm_client, agent_prompt, num_examples, "")

    effective_chunk_size = chunk_size if chunk_size > 0 else ConfigLoader.get("pipeline", "dataset", "chunk_size")
    chunks = chunk_text(supplementary_docs, effective_chunk_size, chunk_overlap)

    if len(chunks) <= 1:
        return _generate_single(lm_client, agent_prompt, num_examples, supplementary_docs)

    per_chunk = max(1, num_examples // len(chunks))
    if per_chunk < 2:
        logger.warning("Too many chunks (%d) for %d examples; falling back to single-shot generation", len(chunks), num_examples)
        return _generate_single(lm_client, agent_prompt, num_examples, supplementary_docs[:effective_chunk_size])

    logger.info("Splitting supplementary docs into %d chunks (size=%d, overlap=%d)", len(chunks), effective_chunk_size, chunk_overlap)
    all_examples = []

    for i, chunk in enumerate(chunks):
        logger.info("Generating examples from chunk %d/%d...", i + 1, len(chunks))
        try:
            chunk_examples = _generate_single(lm_client, agent_prompt, per_chunk, chunk)
            all_examples.extend(chunk_examples)
        except Exception as e:
            logger.warning("Chunk %d generation failed: %s", i + 1, e)
            continue

    if len(all_examples) < num_examples:
        remaining = num_examples - len(all_examples)
        try:
            extra = _generate_single(lm_client, agent_prompt, remaining, supplementary_docs[:effective_chunk_size])
            all_examples.extend(extra)
        except Exception as e:
            logger.warning("Fallback generation failed: %s", e)

    return all_examples[:num_examples]


def _generate_single(lm_client, agent_prompt: str, num_examples: int, doc_text: str = "") -> list:
    """Single-shot dataset generation from a prompt + optional doc text."""
    doc_block = f"\nReference documentation:\n{doc_text}\n" if doc_text else ""
    prompt = (
        f"Generate exactly {num_examples} realistic test scenarios for the following agent prompt.\n"
        f"\nAGENT SYSTEM PROMPT:\n{agent_prompt}\n"
        f"{doc_block}"
        f"\nFor each scenario, provide:\n"
        f'- "input_context": A realistic user query the agent might receive\n'
        f'- "gold_response": The correct answer the agent should return\n'
        f"\nOutput ONLY a raw JSON array of objects with keys 'input_context' and 'gold_response'. "
         f"No markdown, no emojis, no explanations.\n\nJSON ARRAY:"
    )
    raw = lm_client(prompt=prompt)
    raw_text = raw[0] if isinstance(raw, list) else str(raw)
    return extract_and_load_dataset(raw_text)


def curate_dataset(lm_client, examples: list, threshold: float = 7.0, max_examples: int = 0) -> list:
    """Score each example 1-10 using LLM-as-judge, filter below threshold.
    Returns curated examples sorted by score descending.
    If max_examples > 0, returns at most that many top examples."""
    scored = []
    for i, ex in enumerate(examples):
        score = _score_example_quality(lm_client, ex)
        logger.info("Curated example %d/%d: score=%.1f", i + 1, len(examples), score)
        if score >= threshold:
            scored.append((score, ex))

    scored.sort(key=lambda pair: pair[0], reverse=True)
    curated = [ex for _, ex in scored]
    if max_examples > 0 and len(curated) > max_examples:
        curated = curated[:max_examples]
    logger.info("Curated dataset: %d/%d examples passed threshold=%.1f", len(curated), len(examples), threshold)
    return curated


def _score_example_quality(lm_client, example) -> float:
    """Score a single training example 1-10 using LLM-as-judge."""
    prompt = (
        "Rate the quality of this training example from 1 (worst) to 10 (best).\n\n"
        f"Input: {example.input_context}\n"
        f"Expected Output: {getattr(example, 'output_response', getattr(example, 'gold_response', ''))}\n\n"
        "Criteria:\n"
        "- Is the input a realistic user query for the agent?\n"
        "- Is the expected output correct and specific?\n"
        "- Is the pair detailed enough to train on?\n\n"
        "Return ONLY a single number between 1 and 10. No other text."
    )
    try:
        raw = lm_client(prompt=prompt, temperature=0.0, max_tokens=10)
        text = raw[0] if isinstance(raw, list) else str(raw)
        match = re.search(r"(\d+(?:\.\d+)?)", text)
        if match:
            return float(match.group(1))
    except Exception as e:
        logger.warning("Quality scoring failed for example: %s", e)
    return 0.0


def convert_dataset_format(examples: list, fmt: str = "json", supplementary_docs: str = "") -> str:
    """Convert a list of dspy.Examples to the specified output format.
    Supported formats: json, jsonl, alpaca, chatml."""
    serializable = [
        {
            "input_context": ex.input_context,
            "gold_response": getattr(ex, "output_response", getattr(ex, "gold_response", "")),
            "source_context": supplementary_docs or getattr(ex, "source_context", ""),
        }
        for ex in examples
    ]

    if fmt == "json":
        return json.dumps(serializable, indent=2)

    elif fmt == "jsonl":
        return "\n".join(json.dumps(item) for item in serializable)

    elif fmt == "alpaca":
        alpaca_items = []
        for item in serializable:
            alpaca_items.append({
                "instruction": "Respond to the user query based on the agent's system prompt.",
                "input": item["input_context"],
                "output": item["gold_response"],
            })
        return json.dumps(alpaca_items, indent=2)

    elif fmt == "chatml":
        chatml_items = []
        for item in serializable:
            chatml_items.append({
                "messages": [
                    {"role": "user", "content": item["input_context"]},
                    {"role": "assistant", "content": item["gold_response"]},
                ]
            })
        return json.dumps(chatml_items, indent=2)

    else:
        logger.warning("Unknown output format '%s', falling back to json", fmt)
        return json.dumps(serializable, indent=2)


def read_document_file(file_path: str) -> str:
    """Read a document file and return its text content.
    Supports .md, .txt, .json, .pdf, .docx, .html, .pptx."""
    ext = os.path.splitext(file_path)[1].lower()
    try:
        if ext == ".pdf":
            if fitz is None:
                logger.warning("PyMuPDF not installed, skipping PDF: %s", file_path)
                return ""
            doc = fitz.open(file_path)
            text = "\n".join(page.get_text() for page in doc)
            doc.close()
            return text.strip()

        elif ext == ".json":
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return json.dumps(data, indent=2) if isinstance(data, dict) else json.dumps(data, indent=2)

        elif ext == ".docx":
            if DocxDocument is None:
                logger.warning("python-docx not installed, skipping: %s", file_path)
                return ""
            doc = DocxDocument(file_path)
            return "\n".join(p.text for p in doc.paragraphs).strip()

        elif ext == ".html":
            if BeautifulSoup is None:
                logger.warning("beautifulsoup4 not installed, skipping: %s", file_path)
                return ""
            with open(file_path, "r", encoding="utf-8") as f:
                soup = BeautifulSoup(f.read(), "html.parser")
            for tag in soup(["script", "style", "nav", "footer", "header"]):
                tag.decompose()
            return soup.get_text(separator="\n").strip()

        elif ext == ".pptx":
            if Presentation is None:
                logger.warning("python-pptx not installed, skipping: %s", file_path)
                return ""
            prs = Presentation(file_path)
            lines = []
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text"):
                        lines.append(shape.text)
            return "\n".join(lines).strip()

        else:
            with open(file_path, "r", encoding="utf-8") as f:
                return f.read().strip()

    except Exception as e:
        logger.warning("Failed to read document %s: %s", file_path, e)
        return ""


def scan_document_directory(document_dir: str) -> str:
    """Scan a flat directory for supported documents and return their concatenated text.
    Supports .md, .txt, .json, .pdf extensions (non-recursive)."""
    if not document_dir or not os.path.isdir(document_dir):
        return ""

    extensions = ConfigLoader.get("pipeline", "dataset", "document_extensions")
    pieces = []

    for filename in sorted(os.listdir(document_dir)):
        filepath = os.path.join(document_dir, filename)
        if not os.path.isfile(filepath):
            continue
        ext = os.path.splitext(filename)[1].lower()
        if ext in extensions:
            content = read_document_file(filepath)
            if content:
                pieces.append(f"--- {filename} ---\n{content}")

    if not pieces:
        return ""

    return "\n\n".join(pieces)


def extract_markdown_sections(file_path: str) -> dict:
    """Splits a markdown document by its top level or secondary headers."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    sections = {}
    current_header = "General Overview"
    current_text = []

    for line in content.splitlines():
        if line.startswith("#"):
            if current_text:
                sections[current_header] = "\n".join(current_text).strip()
            current_header = line.lstrip("# ").strip()
            current_text = []
        else:
            current_text.append(line)

    if current_text:
        sections[current_header] = "\n".join(current_text).strip()

    return sections


def generate_dynamic_dataset(agent_file_path: str, count: int = 15, lm_client=None) -> list:
    """Extracts sections from markdown and builds targeted synthetic evaluation splits."""
    logger.info(f"Extracting sub-sections from agent profile: {agent_file_path}")

    sections = extract_markdown_sections(agent_file_path)
    dspy_dataset = []

    examples_per_section = max(2, count // len(sections))

    min_body_length = ConfigLoader.get("pipeline", "section", "min_body_length")
    for header, body in sections.items():
        if len(body) < min_body_length:
            continue

        logger.info(f"Generating synthetic cases for documentation segment: [{header}]")
        context_prompt = f"Document Section: {header}\nContent Details:\n{body}"

        try:
            section_examples = generate_dataset_via_lm(
                lm_client=lm_client,
                agent_prompt=context_prompt,
                num_examples=examples_per_section,
            )
            dspy_dataset.extend(section_examples)

        except Exception as e:
            logger.warning(f"Failed to generate specific rows for section {header}: {str(e)}")
            continue

    if not dspy_dataset:
        logger.error("All structural parsing loops failed. Injecting safe baseline dataset.")
        fallback_data = [
            {"input_context": "How do I run tracking on bears and giraffes?",
             "gold_response": "Run python main.py --class-id 21,23"},
            {"input_context": "Can I edit main2.py to add features?",
             "gold_response": "No, main2.py is frozen. All active edits must happen inside main.py."}
        ]
        for item in fallback_data:
            dspy_dataset.append(dspy.Example(**item).with_inputs("input_context"))

    logger.info(f"Total structured synthetic dataset generated successfully: {len(dspy_dataset)} rows.")
    return dspy_dataset


# =====================================================================
# REPORT GENERATION
# =====================================================================

def generate_validation_markdown(file_path, original_prompt, optimized_instruction, history, dataset_size,
                                 optimizer_type="mipro"):
    """Generates a text-based dashboard report with normalized percentage tracking."""
    optimizer_label = optimizer_type.upper() if optimizer_type.lower() in ("mipro", "gepa") else optimizer_type
    raw_baseline = history[0]
    raw_optimized = history[1]

    if raw_baseline > 1.0:
        raw_baseline = raw_baseline / dataset_size
    if raw_optimized > 1.0:
        raw_optimized = raw_optimized / dataset_size

    baseline_pct = min(100.0, raw_baseline * 100.0)
    optimized_pct = min(100.0, raw_optimized * 100.0)
    improvement = optimized_pct - baseline_pct

    baseline_bars = int(baseline_pct // 5)
    optimized_bars = int(optimized_pct // 5)

    report = f"""# {optimizer_label} Optimization Performance Report

## Executive Summary
* **Target File Profile:** `{os.path.basename(file_path)}`
* **Synthetic Evaluation Dataset Size:** {dataset_size} custom scenarios
* **Initial Baseline Performance Score:** `{baseline_pct:.2f}%`
* **Final Optimized Performance Score:** `{optimized_pct:.2f}%`
* **Net Performance Shift:** `{"+" if improvement >= 0 else ""}{improvement:.2f}%`

## Performance Visualization
```text
Baseline Score:  [{'#' * baseline_bars}{'-' * (20 - baseline_bars)}] {baseline_pct:.1f}%
Optimized Score: [{'#' * optimized_bars}{'-' * (20 - optimized_bars)}] {optimized_pct:.1f}%
```

## Compiled Optimized Instructions
Below is the system prompt generated by the {optimizer_label} optimizer to direct your agent:
```text
{optimized_instruction}
```

---
*Report generated successfully on background worker thread.*
"""
    return report


# =====================================================================
# OPTIMIZER FACTORY
# =====================================================================

def _adapt_metric_for_gepa(metric_fn: Callable) -> Callable:
    """Wrap a standard (gold, pred, trace) metric for GEPA.
    GEPA expects a raw float score; it wraps the float into feedback text itself.
    Extra pred_name/pred_trace args from GEPA are dropped.
    """
    def gepa_metric(gold, pred, trace=None, pred_name=None, pred_trace=None):
        if gold is ... or pred is ...:
            logger.warning("GEPA metric received Ellipsis sentinel — returning 0.0")
            return 0.0
        return float(metric_fn(gold, pred, trace))
    return gepa_metric


def _create_teleprompter(optimizer_type: str, metric: Callable, lm_client,
                         task_model=None, **kwargs) -> object:
    """Factory: build and return a configured teleprompter (MIPROv2 or GEPA)."""
    ot = optimizer_type.lower().strip()

    if ot == "mipro":
        return MIPROv2(
            metric=metric,
            prompt_model=task_model,
            task_model=task_model,
            num_candidates=kwargs.get("num_candidates", ConfigLoader.get("pipeline", "mipro", "num_candidates")),
            auto=kwargs.get("auto", None),
            seed=kwargs.get("seed", ConfigLoader.get("pipeline", "mipro", "seed")),
        )

    elif ot == "gepa":
        gepa_cfg = ConfigLoader.get("pipeline", "gepa")
        gepa_kwargs = dict(
            metric=_adapt_metric_for_gepa(metric),
            reflection_lm=lm_client,
            seed=kwargs.get("seed", gepa_cfg.get("seed", 0)),
            num_threads=gepa_cfg.get("num_threads", 1),
        )
        if "max_metric_calls" in gepa_cfg:
            gepa_kwargs["max_metric_calls"] = gepa_cfg["max_metric_calls"]
            gepa_kwargs["auto"] = None
        else:
            gepa_kwargs["auto"] = kwargs.get("auto", gepa_cfg.get("auto", "light"))
        return GEPA(**gepa_kwargs)

    else:
        raise ValueError(f"Unknown optimizer_type '{optimizer_type}'. Must be 'mipro' or 'gepa'.")


def _extract_optimized_instructions(teleprompter, compiled_program, optimizer_type: str) -> str:
    """Extract the optimized instruction text from a compiled program.
    Handles both MIPROv2 and GEPA storage paths."""
    for attr_path in [
        lambda p: p.signature.instructions,
        lambda p: p.program.signature.instructions,
        lambda p: p.predictor.signature.instructions,
        lambda p: p.program.predictor.signature.instructions,
    ]:
        try:
            val = attr_path(compiled_program)
            if val and val.strip():
                return val
        except (AttributeError, TypeError):
            continue

    if hasattr(teleprompter, 'instruction_history') and teleprompter.instruction_history:
        last = teleprompter.instruction_history[-1]
        if last and last.strip():
            return last

    logger.warning("Could not extract optimized instructions from compiled %s program", optimizer_type)
    return str(compiled_program)


def _extract_optimized_demos(compiled_program, optimizer_type: str) -> list:
    """Extract demos from a compiled program. GEPA has none."""
    if optimizer_type.lower().strip() == "gepa":
        return []
    return getattr(compiled_program, 'demos', [])


# =====================================================================
# PIPELINE FUNCTIONS
# =====================================================================

def _get_lm_client(provider: str, model: str, registry=None):
    """Get a language model client via registry skill or fallback without calling dspy.configure()."""
    if registry:
        connection_skill = registry.get_skill("model_connector")
        return connection_skill.execute(provider=provider, model=model)
    else:
        from core.skills.model_connector import LMStudioLM
        cfg = ConfigLoader.get("providers", "lm-studio")
        return LMStudioLM(
            model=model if model else cfg["default_model"],
            api_base=cfg["api_base"]
        )


def run_optimization_pipeline(agent_markdown_path: str, provider: str = "lm-studio", model: str = "",
                              lm_client=None, registry=None, optimizer_type: str = "mipro",
                              document_dir: str = "") -> str:
    """Run optimization on an agent markdown file using the selected optimizer (MIPROv2 or GEPA).
    Optionally accepts a document_dir for supplementary reference documentation.
    When docs are provided, the dataset is auto-validated before optimization."""
    if not os.path.exists(agent_markdown_path):
        return f"Error: Target file not found at path: {agent_markdown_path}"

    logger.info("Compiling local configurations...")

    with open(agent_markdown_path, "r", encoding="utf-8") as f:
        original_prompt = f.read()

    backup_path = f"{agent_markdown_path}{ConfigLoader.get("file_suffixes", "backup")}"
    with open(backup_path, "w", encoding="utf-8") as f:
        f.write(original_prompt)

    if lm_client is None:
        lm_client = _get_lm_client(provider, model, registry)

    prompt_body = original_prompt
    frontmatter_match = re.match(r"^(---\s*\n[\s\S]*?\n---\s*\n)", original_prompt)
    if frontmatter_match:
        prompt_body = original_prompt[len(frontmatter_match.group(1)):]

    current_instructions = prompt_body.strip()
    logger.info(f"Read current prompt text body ({len(current_instructions)} chars).")

    supplementary_docs = scan_document_directory(document_dir) if document_dir else ""
    if supplementary_docs:
        logger.info("Loaded supplementary docs (%d chars) from: %s", len(supplementary_docs), document_dir)

    with dspy.context(lm=lm_client):
        trainset = generate_dataset_via_lm(
            lm_client=lm_client,
            agent_prompt=current_instructions,
            num_examples=ConfigLoader.get("pipeline", "dataset", "num_examples"),
            supplementary_docs=supplementary_docs,
        )

        generated_dataset_path = os.path.splitext(agent_markdown_path)[0] + ConfigLoader.get("file_suffixes", "generated_dataset")
        try:
            serializable = [
                {
                    "input_context": ex.input_context,
                    "gold_response": getattr(ex, "output_response", getattr(ex, "gold_response", "")),
                    "source_context": supplementary_docs,
                }
                for ex in trainset
            ]
            with open(generated_dataset_path, "w") as f:
                json.dump(serializable, f, indent=2)
            logger.info("Generated dataset saved to %s (%d examples)", generated_dataset_path, len(trainset))
        except Exception as e:
            logger.warning("Failed to save generated dataset: %s", e)

        # Auto-validate dataset before running the optimizer
        val_report = ""
        try:
            val_cfg = ConfigLoader.get("pipeline", "dataset_validation")
        except KeyError:
            val_cfg = {"enabled": True}
        if val_cfg.get("enabled", True):
            logger.info("Running automatic dataset validation...")
            try:
                val_report = run_dataset_validation_pipeline(
                    dataset_path=generated_dataset_path,
                    agent_markdown_path=agent_markdown_path,
                    provider=provider,
                    model=model,
                    lm_client=lm_client,
                    registry=registry,
                )
                logger.info("Dataset validation complete:\n%s", val_report)
                if "FAIL" in val_report and val_cfg.get("on_failure", "warn") == "abort":
                    return f"Dataset validation FAILED. Aborting optimization.\n\n{val_report}"
            except Exception as val_err:
                logger.warning("Auto-validation failed (continuing): %s", val_err)

        customized_signature = DynamicAgentSignature.with_instructions(current_instructions)
        base_program = dspy.Predict(customized_signature)

        evaluator = Evaluate(devset=trainset, metric=secure_universal_llm_metric, display_progress=False)
        logger.info("Phase: Baseline evaluation starting (%d examples)...", len(trainset))
        baseline_result = evaluator(base_program)
        baseline_score = float(getattr(baseline_result, 'score', baseline_result))
        logger.info(f"Phase: Baseline Score: {baseline_score:.1f}%")

        teleprompter = _create_teleprompter(
            optimizer_type=optimizer_type,
            metric=secure_universal_llm_metric,
            lm_client=lm_client,
            task_model=lm_client,
        )
        compile_kwargs = dict(trainset=trainset, valset=trainset)
        if optimizer_type.lower().strip() == "mipro":
            compile_kwargs.update(
                minibatch=ConfigLoader.get("pipeline", "mipro", "minibatch"),
                num_trials=ConfigLoader.get("pipeline", "mipro", "num_trials"),
                max_bootstrapped_demos=ConfigLoader.get("pipeline", "mipro", "max_bootstrapped_demos"),
            )
        logger.info("Phase: %s compile starting...", optimizer_type.upper())
        try:
            compiled_program = teleprompter.compile(base_program.deepcopy(), **compile_kwargs)
        except Exception as e:
            if "ellipsis" in str(e).lower():
                return f"GEPA optimization failed due to an LM output parsing issue: {e}"
            raise
        logger.info("Phase: %s compile complete.", optimizer_type.upper())

        logger.info("Phase: Optimized evaluation starting...")
        optimized_result = evaluator(compiled_program)
        optimized_score = float(getattr(optimized_result, 'score', optimized_result))
        logger.info(f"Phase: Optimized Score: {optimized_score:.1f}%")

        logger.info("Phase: Extracting optimized instructions...")
        optimized_instructions = _extract_optimized_instructions(teleprompter, compiled_program, optimizer_type)
        logger.info("Phase: Extracted instruction (%d chars). Generating report...", len(optimized_instructions))
        report = generate_validation_markdown(
            file_path=agent_markdown_path,
            original_prompt=original_prompt,
            optimized_instruction=optimized_instructions,
            history=[baseline_score, optimized_score],
            dataset_size=len(trainset),
            optimizer_type=optimizer_type,
        )
        logger.info("Phase: Report generated.")

    try:
        report_dir = os.path.dirname(os.path.abspath(agent_markdown_path))
        report_file = os.path.join(report_dir, ConfigLoader.get("file_suffixes", "report"))
        logger.info("Phase: Writing report to %s", report_file)
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(report)
        logger.info(f"Report saved to {report_file}")
    except Exception as report_error:
        logger.error(f"Failed to write report to disk: {str(report_error)}")

    if optimized_score >= baseline_score:
        logger.info("Optimized text beat or matched baseline. Updating file layout...")
        optimized_demos = _extract_optimized_demos(compiled_program, optimizer_type)
        if registry:
            file_skill = registry.get_skill("surgical_file_modifier")
            file_skill.execute(
                file_path=agent_markdown_path,
                new_prompt=optimized_instructions,
                demos=optimized_demos
            )
        else:
            compiled_prompt_path = os.path.splitext(agent_markdown_path)[0] + ConfigLoader.get("file_suffixes", "compiled_prompt")
            demo_blocks = []
            for idx, demo in enumerate(optimized_demos):
                ctx = demo.get('input_context', demo.get('input', ''))
                resp = demo.get('output_response', demo.get('output', ''))
                if ctx and resp:
                    demo_blocks.append(f"### Example Case {idx + 1}\nInput: {ctx}\nOutput: {resp}\n")
            compiled_content = f"# COMPILED AGENT SYSTEM INSTRUCTIONS\n{optimized_instructions}\n\n## Bootstrapped Few-Shot Demonstrations\n" + (
                "\n".join(demo_blocks) if demo_blocks else "No high-scoring demos isolated.")
            with open(compiled_prompt_path, "w", encoding="utf-8") as f:
                f.write(compiled_content.strip())
        val_prefix = f"\n--- Dataset Validation ---\n{val_report}\n" if val_report else ""
        return f"{val_prefix}Success! Baseline: {baseline_score:.0f}%, Optimized: {optimized_score:.0f}%."
    else:
        logger.info("Proposed changes didn't beat the baseline. File left untouched.")
        val_prefix = f"\n--- Dataset Validation ---\n{val_report}\n" if val_report else ""
        return f"{val_prefix}Existing layout scored higher ({baseline_score:.0f}%) than proposed variations. File left untouched."


def run_specification_pipeline(spec_json_path: str, provider: str = "lm-studio", model: str = "",
                               lm_client=None, registry=None) -> str:
    """Optimize JSON schema documentation fields using DSPy while preserving structure."""
    if not os.path.exists(spec_json_path):
        return f"Error: Target file not found at path: {spec_json_path}"

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        with dspy.context(lm=lm_client):
            optimizer_program = dspy.Predict(SpecDocumentationSignature)

            def dspy_optimization_worker(text_to_optimize: str) -> str:
                response = optimizer_program(raw_description=text_to_optimize)
                return response.optimized_description.strip()

            if registry:
                spec_skill = registry.get_skill("spec_structural_isolation")
                spec_skill.execute(file_path=spec_json_path, optimize_callback=dspy_optimization_worker)
            else:
                with open(spec_json_path, "r", encoding="utf-8") as f:
                    spec_data = json.load(f)

                def walk_and_optimize(node):
                    if isinstance(node, dict):
                        new_dict = {}
                        for key, value in node.items():
                            if key in ["description", "summary", "title"] and isinstance(value, str) and value.strip():
                                new_dict[key] = dspy_optimization_worker(value)
                            else:
                                new_dict[key] = walk_and_optimize(value)
                        return new_dict
                    elif isinstance(node, list):
                        return [walk_and_optimize(item) for item in node]
                    return node

                optimized_spec = walk_and_optimize(spec_data)
                base, ext = os.path.splitext(spec_json_path)
                optimized_file_path = f"{base}{ConfigLoader.get("file_suffixes", "optimized")}{ext}"
                with open(optimized_file_path, "w", encoding="utf-8") as f:
                    json.dump(optimized_spec, f, indent=2)

        return f"Success! Specification metadata at '{spec_json_path}' optimized successfully."
    except Exception as e:
        logger.exception("Specification optimization encountered a failure:")
        return f"Specification optimization failed: {str(e)}"


def run_code_optimization_pipeline(skill_file_path: str, provider: str = "lm-studio", model: str = "",
                                   lm_client=None, registry=None, optimizer_type: str = "mipro") -> str:
    """Optimize Python skill code via MIPROv2 or GEPA with subprocess pytest metric validation."""
    if not os.path.exists(skill_file_path):
        return f"Error: Target file not found at path: {skill_file_path}"
    if not skill_file_path.endswith(".py"):
        return f"Error: Can only optimize valid Python (.py) source files."

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        with open(skill_file_path, "r", encoding="utf-8") as f:
            current_source_code = f.read()

        code_example = dspy.Example(input_context=current_source_code, output_response="PASS").with_inputs(
            "input_context")
        mock_code_set = [code_example]

        def dynamic_pytest_reward_metric(gold, pred, trace=None):
            clean_code = pred.optimized_python_code.strip()
            if clean_code.startswith("```python"):
                clean_code = re.sub(r"^```python|```$", "", clean_code, flags=re.MULTILINE).strip()
            elif clean_code.startswith("```"):
                clean_code = re.sub(r"^```|```$", "", clean_code, flags=re.MULTILINE).strip()

            temp_test_file = skill_file_path + ".tmp"
            backup_file = skill_file_path + ".bak"

            try:
                with open(temp_test_file, "w", encoding="utf-8") as f:
                    f.write(clean_code)

                syntax_check = subprocess.run(
                    [sys.executable, "-m", "py_compile", temp_test_file],
                    capture_output=True
                )
                if syntax_check.returncode != 0:
                    return 0.0

                shutil.copyfile(skill_file_path, backup_file)
                shutil.copyfile(temp_test_file, skill_file_path)

                test_suite_run = subprocess.run(
                    ["pytest", "tests/test_skills.py"],
                    capture_output=True,
                    text=True
                )

                shutil.copyfile(backup_file, skill_file_path)

                if os.path.exists(temp_test_file):
                    os.remove(temp_test_file)
                if os.path.exists(backup_file):
                    os.remove(backup_file)

                if test_suite_run.returncode == 0:
                    return 1.0
                else:
                    return 0.0

            except Exception as e:
                logger.error(f"Metric failure: {str(e)}")
                if os.path.exists(backup_file):
                    shutil.copyfile(backup_file, skill_file_path)
                for f_path in [temp_test_file, backup_file]:
                    if os.path.exists(f_path):
                        os.remove(f_path)
                return 0.0

        with dspy.context(lm=lm_client):
            code_program = dspy.Predict(CodeOptimizationSignature)

            teleprompter = _create_teleprompter(
                optimizer_type=optimizer_type,
                metric=dynamic_pytest_reward_metric,
                lm_client=lm_client,
                task_model=lm_client,
                num_candidates=ConfigLoader.get("pipeline", "mipro", "num_candidates_code"),
            )
            compile_kwargs = dict(trainset=mock_code_set, valset=mock_code_set)
            if optimizer_type.lower().strip() == "mipro":
                compile_kwargs.update(
                    minibatch=ConfigLoader.get("pipeline", "mipro", "minibatch"),
                    num_trials=ConfigLoader.get("pipeline", "mipro", "num_trials_code"),
                    max_bootstrapped_demos=ConfigLoader.get("pipeline", "mipro", "max_bootstrapped_demos_code"),
                )
            compiled_code_program = teleprompter.compile(code_program, **compile_kwargs)

            final_optimized_code = compiled_code_program.optimized_python_code.strip()

        if final_optimized_code.startswith("```python"):
            final_optimized_code = re.sub(r"^```python|```$", "", final_optimized_code, flags=re.MULTILINE).strip()
        elif final_optimized_code.startswith("```"):
            final_optimized_code = re.sub(r"^```|```$", "", final_optimized_code, flags=re.MULTILINE).strip()

        if len(final_optimized_code) < 50:
            return "Optimizer returned an uncharacteristically short code string. Overwrite prevented."

        with open(skill_file_path, "w", encoding="utf-8") as f:
            f.write(final_optimized_code)

        return f"Success! '{skill_file_path}' has been autonomously optimized, security-vetted, and re-written."

    except Exception as e:
        return f"Code optimization pipeline failed: {str(e)}"


def run_verification_pipeline(agent_markdown_path: str, provider: str = "lm-studio", model: str = "",
                              lm_client=None, registry=None,
                              original_markdown_path: str = "") -> str:
    """Independent QA evaluation on an optimized file to verify generalization."""
    if not os.path.exists(agent_markdown_path):
        return f"Error: Target file not found at path: {agent_markdown_path}"

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        generated_dataset_path = os.path.splitext(agent_markdown_path)[0] + ConfigLoader.get("file_suffixes", "generated_dataset")
        if not os.path.exists(generated_dataset_path):
            generated_dataset_path = ""

        kwargs = dict(
            agent_markdown_path=agent_markdown_path,
            original_markdown_path=original_markdown_path,
            test_set_path=generated_dataset_path,
            lm_client=lm_client,
        )

        if registry:
            verifier_skill = registry.get_skill("prompt_verifier")
            result = verifier_skill.execute(**kwargs)
        else:
            from core.skills.verifier import VerificationSkill
            verifier_skill = VerificationSkill()
            result = verifier_skill.execute(**kwargs)

        baseline_note = f" (vs {result.get('baseline_source', 'default')})"
        return (
            f"[QA Audit Complete for {agent_markdown_path}]\n"
            f"- Baseline Accuracy on New Data: {result['baseline_score']:.1f}%\n"
            f"- Optimized Accuracy on New Data: {result['optimized_score']:.1f}%\n"
            f"Verification {result['verdict']}: {result['detail']}{baseline_note}"
        )

    except Exception as e:
        logger.exception("QA verification sub-routine failed:")
        return f"QA verification sub-routine failed: {str(e)}"


def run_dataset_generation_pipeline(agent_markdown_path: str, provider: str = "lm-studio", model: str = "",
                                    lm_client=None, registry=None, num_examples: int = 5,
                                    document_dir: str = "", curate: bool = False,
                                    curation_threshold: float = 0.0,
                                    output_format: str = "json") -> str:
    """Generate a synthetic training dataset from an agent markdown file without running optimization.

    Supports chunking for large docs, LLM-as-judge curation, and multiple output formats.
    Optionally accepts a document_dir for supplementary reference documentation."""
    if not os.path.exists(agent_markdown_path):
        return f"Error: Target file not found at path: {agent_markdown_path}"

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        with open(agent_markdown_path, "r", encoding="utf-8") as f:
            original_prompt = f.read()

        prompt_body = original_prompt
        frontmatter_match = re.match(r"^(---\s*\n[\s\S]*?\n---\s*\n)", original_prompt)
        if frontmatter_match:
            prompt_body = original_prompt[len(frontmatter_match.group(1)):]

        current_instructions = prompt_body.strip()
        supplementary_docs = scan_document_directory(document_dir) if document_dir else ""
        if supplementary_docs:
            logger.info("Loaded supplementary docs (%d chars) from: %s", len(supplementary_docs), document_dir)

        trainset = generate_dataset_via_lm(
            lm_client=lm_client,
            agent_prompt=current_instructions,
            num_examples=num_examples,
            supplementary_docs=supplementary_docs,
        )

        # Quality curation step
        if curate or curation_threshold > 0:
            effective_threshold = curation_threshold if curation_threshold > 0 else \
                ConfigLoader.get("pipeline", "curation", "threshold")
            logger.info("Running LLM-as-judge curation (threshold=%.1f)...", effective_threshold)
            trainset = curate_dataset(lm_client, trainset, threshold=effective_threshold)

        # Build output path
        ext_suffix = ConfigLoader.get("file_suffixes", "generated_dataset")
        base_path = os.path.splitext(agent_markdown_path)[0] + ext_suffix

        # Adjust path for non-json formats
        if output_format == "jsonl":
            generated_dataset_path = base_path.replace(".json", ".jsonl")
        elif output_format in ("alpaca", "chatml"):
            generated_dataset_path = base_path.replace(".json", f"_{output_format}.json")
        else:
            generated_dataset_path = base_path

        # Convert to requested format
        output_text = convert_dataset_format(
            trainset, fmt=output_format, supplementary_docs=supplementary_docs
        )

        with open(generated_dataset_path, "w", encoding="utf-8") as f:
            f.write(output_text)

        result = f"Success! Generated {len(trainset)} examples saved to {generated_dataset_path} (format: {output_format})"
        if curate or curation_threshold > 0:
            result += f"\nCuration threshold: {curation_threshold if curation_threshold > 0 else ConfigLoader.get('pipeline', 'curation', 'threshold')}"
        return result

    except Exception as e:
        logger.exception("Dataset generation pipeline failed:")
        return f"Dataset generation pipeline failed: {str(e)}"


# =====================================================================
# DATASET VALIDATION PIPELINE
# =====================================================================


def _compute_embedding_diversity(examples: list) -> float | None:
    """Stub: always returns None to avoid sentence-transformers download hangs.
    Re-enable by pre-downloading the model with:
        python -c \"from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')\"
    """
    logger.info("Embedding diversity check disabled (use pre-downloaded model to enable).")
    return None


def run_dataset_validation_pipeline(dataset_path: str, agent_markdown_path: str,
                                    provider: str = "lm-studio", model: str = "",
                                    lm_client=None, registry=None,
                                    document_dir: str = "") -> str:
    """Validate a generated dataset against four quality criteria.
    Returns a structured markdown report with per-check PASS/FAIL results."""
    if not os.path.exists(dataset_path):
        return f"Error: Dataset file not found at path: {dataset_path}"
    if not os.path.exists(agent_markdown_path):
        return f"Error: Agent file not found at path: {agent_markdown_path}"

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        with open(agent_markdown_path, "r", encoding="utf-8") as f:
            agent_content = f.read()
        prompt_body = agent_content
        frontmatter_match = re.match(r"^(---\s*\n[\s\S]*?\n---\s*\n)", agent_content)
        if frontmatter_match:
            prompt_body = agent_content[len(frontmatter_match.group(1)):]
        current_instructions = prompt_body.strip()

        with open(dataset_path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)

        if not isinstance(raw_data, list) or len(raw_data) == 0:
            return "Error: Dataset is empty or invalid."

        examples = []
        for item in raw_data:
            ex = dspy.Example(
                input_context=item.get("input_context", ""),
                output_response=item.get("gold_response", ""),
                source_context=item.get("source_context", ""),
            ).with_inputs("input_context")
            examples.append(ex)

        try:
            cfg = ConfigLoader.get("pipeline", "dataset_validation")
        except KeyError:
            cfg = {}
        alignment_threshold = cfg.get("alignment_threshold", 80.0)
        diversity_threshold = cfg.get("diversity_threshold", 0.75)
        baseline_min = cfg.get("baseline_min", 40.0)
        baseline_max = cfg.get("baseline_max", 70.0)
        neg_class_min = cfg.get("negative_class_min", 15.0)

        results = {}

        with dspy.context(lm=lm_client):
            # --- 1. Alignment Check ---
            logger.info("Running alignment check on %d examples...", len(examples))
            validator = dspy.Predict(DatasetValidatorSignature)
            aligned = 0
            total_hardness = 0
            adversarial_count = 0
            for ex in examples:
                try:
                    v = validator(
                        agent_documentation=current_instructions,
                        input_context=ex.input_context,
                        gold_response=ex.output_response,
                    )
                    solvable = "YES" in v.is_solvable.upper()
                    label_correct = "YES" in v.is_label_correct.upper()
                    if solvable and label_correct:
                        aligned += 1
                    try:
                        total_hardness += int(v.hardness_score)
                    except (ValueError, TypeError):
                        total_hardness += 3
                    if "YES" in v.is_adversarial.upper():
                        adversarial_count += 1
                except Exception as e:
                    logger.warning("Alignment check failed for example: %s", e)
                    continue

            alignment_pct = (aligned / len(examples)) * 100 if examples else 0.0
            avg_hardness = total_hardness / max(1, len(examples))
            neg_class_pct = (adversarial_count / len(examples)) * 100 if examples else 0.0
            alignment_pass = alignment_pct >= alignment_threshold
            results["alignment"] = {
                "pass": alignment_pct >= alignment_threshold,
                "value": f"{alignment_pct:.1f}%",
                "threshold": f"≥{alignment_threshold:.0f}%",
                "detail": f"{aligned}/{len(examples)} examples passed LLM judge",
            }
            results["avg_hardness"] = f"{avg_hardness:.1f}/5.0"
            results["negative_class"] = {
                "pass": neg_class_pct >= neg_class_min,
                "value": f"{neg_class_pct:.1f}%",
                "threshold": f"≥{neg_class_min:.0f}%",
                "detail": f"{adversarial_count}/{len(examples)} adversarial cases detected",
            }

            # --- 2. Diversity Check ---
            logger.info("Computing embedding diversity...")
            diversity_score = _compute_embedding_diversity(examples)
            if diversity_score is None:
                results["diversity"] = {
                    "pass": False,
                    "value": "N/A",
                    "threshold": f"<{diversity_threshold}",
                    "detail": "SKIPPED — sentence-transformers not installed or computation failed",
                }
            else:
                diversity_pass = diversity_score < diversity_threshold
                results["diversity"] = {
                    "pass": diversity_pass,
                    "value": f"{diversity_score:.3f}",
                    "threshold": f"<{diversity_threshold}",
                    "detail": "Mean pairwise cosine similarity",
                }

            # --- 3. Baseline Failure Test ---
            logger.info("Running baseline failure test...")
            try:
                customized_signature = DynamicAgentSignature.with_instructions(current_instructions)
                base_program = dspy.Predict(customized_signature)
                evaluator = Evaluate(devset=examples, metric=secure_universal_llm_metric, display_progress=False)
                baseline_result = evaluator(base_program)
                baseline_acc = float(getattr(baseline_result, 'score', baseline_result))
                baseline_acc = baseline_acc / len(examples)
                baseline_acc_pct = min(100.0, baseline_acc * 100.0)
                baseline_pass = baseline_min <= baseline_acc_pct <= baseline_max
                results["baseline"] = {
                    "pass": baseline_pass,
                    "value": f"{baseline_acc_pct:.1f}%",
                    "threshold": f"{baseline_min:.0f}%-{baseline_max:.0f}%",
                    "detail": f"Unoptimized agent accuracy on dataset",
                }
            except Exception as e:
                logger.warning("Baseline test failed: %s", e)
                results["baseline"] = {
                    "pass": False,
                    "value": "ERROR",
                    "threshold": f"{baseline_min:.0f}%-{baseline_max:.0f}%",
                    "detail": f"Failed to run: {str(e)}",
                }

        all_pass = all(v["pass"] for v in results.values() if isinstance(v, dict) and "pass" in v)
        verdict = "PASS" if all_pass else "FAIL"

        report = f"""# Dataset Validation Report

## Summary
* **Dataset:** `{os.path.basename(dataset_path)}`
* **Agent File:** `{os.path.basename(agent_markdown_path)}`
* **Total Examples:** {len(examples)}
* **Avg Hardness:** {results.get("avg_hardness", "N/A")}
* **Overall Verdict:** **{verdict}**

## Results

### 1. Alignment Check
* **Status:** {'PASS' if results['alignment']['pass'] else 'FAIL'}
* **Score:** {results['alignment']['value']} (threshold: {results['alignment']['threshold']})
* **Detail:** {results['alignment']['detail']}

### 2. Semantic Diversity
* **Status:** {'PASS' if results['diversity']['pass'] else 'FAIL'}
* **Score:** {results['diversity']['value']} (threshold: {results['diversity']['threshold']})
* **Detail:** {results['diversity']['detail']}

### 3. Baseline Failure Test
* **Status:** {'PASS' if results['baseline']['pass'] else 'FAIL'}
* **Score:** {results['baseline']['value']} (threshold: {results['baseline']['threshold']})
* **Detail:** {results['baseline']['detail']}

### 4. Negative Class Ratio
* **Status:** {'PASS' if results['negative_class']['pass'] else 'FAIL'}
* **Score:** {results['negative_class']['value']} (threshold: {results['negative_class']['threshold']})
* **Detail:** {results['negative_class']['detail']}
"""

        try:
            base = os.path.splitext(dataset_path)[0]
            report_path = base + ConfigLoader.get("file_suffixes", "validation_report")
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report)
            logger.info("Validation report saved to %s", report_path)
        except Exception as e:
            logger.warning("Failed to save validation report: %s", e)

        return report.strip()

    except Exception as e:
        logger.exception("Dataset validation pipeline failed:")
        return f"Dataset validation pipeline failed: {str(e)}"


# =====================================================================
# SECTION OPTIMIZATION SIGNATURES
# =====================================================================

class SpecSectionSignature(dspy.Signature):
    raw_section = dspy.InputField(desc="The original raw markdown section text including its header.")
    optimized_section = dspy.OutputField(
        desc="The revised, clarified, and optimized markdown section. Preserve all code blocks and key facts.")


SpecSectionSignature.__doc__ = PromptLoader.get("signatures", "SpecSectionSignature")


class SpecSectionQualitySignature(dspy.Signature):
    raw_section = dspy.InputField(desc="The original unmodified section text.")
    optimized_section = dspy.InputField(desc="The optimized version of the section.")
    quality_score = dspy.OutputField(desc="An integer from 0 to 100 indicating how much the optimized version improves quality.")


SpecSectionQualitySignature.__doc__ = PromptLoader.get("signatures", "SpecSectionQualitySignature")


# =====================================================================
# SECTION UTILITIES
# =====================================================================

def extract_sections_from_markdown(file_path: str) -> list:
    """Parse a markdown file into sections by ## headers.
    Returns list of dicts with keys: header, body, full_text.
    The first section (before any ##) is treated as the document overview.
    """
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    sections = []
    parts = re.split(r'\n(?=## )', content)

    for i, part in enumerate(parts):
        part = part.strip()
        if not part:
            continue

        lines = part.split('\n')
        header_line = lines[0] if lines else ""

        if header_line.startswith('## '):
            header = header_line
            body = '\n'.join(lines[1:]).strip()
        elif i == 0:
            header = "# Overview"
            body = part
        else:
            header = "# Section"
            body = part

        if len(body) >= ConfigLoader.get("pipeline", "section", "min_section_length"):
            sections.append({
                "header": header,
                "body": body,
                "full_text": part,
                "index": i
            })

    return sections


def compute_text_similarity(original: str, optimized: str) -> float:
    """Compute a similarity ratio between 0.0 and 1.0 using difflib sequence matcher."""
    return difflib.SequenceMatcher(None, original, optimized).ratio()


# =====================================================================
# SECTION OPTIMIZATION PIPELINE
# =====================================================================

def run_section_optimization_pipeline(agents_markdown_path: str, provider: str = "lm-studio",
                                      model: str = "", lm_client=None, registry=None) -> str:
    """Parse an AGENTS markdown file into sections, optimize each independently,
    and output a side-by-side original-vs-optimized comparison document.
    """
    if not os.path.exists(agents_markdown_path):
        return f"Error: Target file not found at path: {agents_markdown_path}"

    try:
        if lm_client is None:
            lm_client = _get_lm_client(provider, model, registry)

        sections = extract_sections_from_markdown(agents_markdown_path)
        logger.info(f"Extracted {len(sections)} sections from {agents_markdown_path}")

        comparison_lines = []
        optimized_blocks = []

        with dspy.context(lm=lm_client):
            section_optimizer = dspy.Predict(SpecSectionSignature)
            quality_judge = dspy.Predict(SpecSectionQualitySignature)

            for sec in sections:
                header = sec["header"]
                body = sec["body"]
                full = sec["full_text"]
                logger.info(f"Processing section: {header}")

                # 1. Score the original
                try:
                    baseline_judge = quality_judge(
                        raw_section=full,
                        optimized_section=full
                    )
                    baseline_score = int(re.search(r'\d+', str(baseline_judge.quality_score)).group())
                except Exception:
                    baseline_score = ConfigLoader.get("pipeline", "section", "default_baseline_score")

                # 2. Optimize the section
                try:
                    optimized_result = section_optimizer(raw_section=full)
                    optimized_text = optimized_result.optimized_section.strip()
                except Exception as e:
                    logger.warning(f"Optimization failed for {header}: {e}")
                    optimized_text = body

                # 3. Score the optimized version
                try:
                    scored = quality_judge(
                        raw_section=full,
                        optimized_section=optimized_text
                    )
                    optimized_score = int(re.search(r'\d+', str(scored.quality_score)).group())
                except Exception:
                    optimized_score = baseline_score

                # 4. Compute edit distance ratio
                similarity = compute_text_similarity(body, optimized_text)
                edit_pct = int((1.0 - similarity) * 100)

                # Use the higher of judge score and edit distance for the displayed percentage
                display_pct = max(optimized_score - baseline_score, edit_pct)
                display_pct = max(0, min(100, display_pct))

                change_note = ""
                if display_pct <= ConfigLoader.get("pipeline", "section", "no_change_threshold"):
                    change_note = "No change"

                # Reconstruct optimized block for full-doc output.
                # The LM may return the header inside optimized_text, so strip any leading
                # header match to avoid duplicating it.
                if optimized_text.startswith(header):
                    optimized_body = optimized_text[len(header):].strip()
                else:
                    optimized_body = optimized_text
                reconstructed = f"{header}\n{optimized_body}"
                optimized_blocks.append(reconstructed)

                # Build comparison block
                comparison_lines.append(f"{header}")
                comparison_lines.append("-- ORIGINAL")
                comparison_lines.append(body)
                comparison_lines.append("")
                if change_note:
                    comparison_lines.append(f"-- OPTIMIZED ({display_pct}%) {change_note}")
                else:
                    comparison_lines.append(f"-- OPTIMIZED ({display_pct}%)")
                comparison_lines.append(optimized_text)
                comparison_lines.append("")

        output = "\n".join(comparison_lines)
        reconstructed_doc = "\n\n".join(optimized_blocks)

        output_dir = os.path.dirname(os.path.abspath(agents_markdown_path))
        base_name = os.path.splitext(os.path.basename(agents_markdown_path))[0]
        suffixes = ConfigLoader.get("file_suffixes")

        try:
            comparison_path = os.path.join(output_dir, f"{base_name}{suffixes['section_comparison']}")
            with open(comparison_path, "w", encoding="utf-8") as f:
                f.write(output)
            logger.info(f"Section comparison saved to {comparison_path}")
        except Exception as e:
            logger.error(f"Failed to save comparison output: {e}")

        try:
            optimized_path = os.path.join(output_dir, f"{base_name}{suffixes['optimized']}.md")
            with open(optimized_path, "w", encoding="utf-8") as f:
                f.write(reconstructed_doc)
            logger.info(f"Reconstructed optimized document saved to {optimized_path}")
        except Exception as e:
            logger.error(f"Failed to save reconstructed optimized doc: {e}")

        return output

    except Exception as e:
        logger.exception("Section optimization pipeline failed:")
        return f"Section optimization pipeline failed: {str(e)}"
